  steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-northeast2-docker.pkg.dev/heiwadai/server/heiwadai-server:$COMMIT_SHA', '-f', './docker/Dockerfile/server/Dockerfile.prod', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast2-docker.pkg.dev/heiwadai/server/heiwadai-server:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'heiwadai-server'
    - '--image'
    - 'asia-northeast2-docker.pkg.dev/heiwadai/server/heiwadai-server:$COMMIT_SHA'
    - '--region'
    - 'asia-northeast2'
  images:
  - 'asia-northeast2-docker.pkg.dev/heiwadai/server/heiwadai-server:$COMMIT_SHA'
  options:
    logging: CLOUD_LOGGING_ONLY