version: '3.8'
services:
  server:
    container_name: heiwadai-server.prod
    tty: true
    env_file: ./.env.prod
    build:
      context: .
      dockerfile: ./docker/Dockerfile/server/Dockerfile.prod
    ports:
      - 3000:3000

