version: '3.8'
services:
  server:
    container_name: heiwadai-server
    tty: true
    env_file: ./.env
    build:
      context: .
      dockerfile: ./docker/Dockerfile/server/Dockerfile
    volumes:
      - ./docker/data/server/bin:/go/bin:Z
      - ./server:/server
    ports:
      - 3000:3000
  # redis:
  #   container_name: heiwadai-redis
  #   image: redis:7.0.12
  #   restart: unless-stopped
  #   ports:
  #     - ${REDISPORT}:${REDISPORT}
  #   environment:
  #     REDIS_ARGS: --save 5 30 --appendonly yes
  #   volumes:
  #     - ./docker/data/redis/data:/data:Z
  # rabbitmq:
  #   # -management を付与したイメージの場合、15672ポートでManagement Plugin(Web UIのようなもの)が利用できるようになる
  #   image: rabbitmq:3.12.1-management
  #   hostname: rabbitmq
  #   container_name: heiwadai-rabbitmq
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
  #   # ユーザ名/パスワードの設定
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
  #     - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
  #   # データの永続化
  #   volumes:
  #     - ./docker/data/rabbitmq/data:/var/lib/rabbitmq

  # db:
  #   container_name: supabase-db
  #   image: supabase/postgres:15.1.0.90
  #   restart: unless-stopped
  #   ports:
  #     - ${PSQL_PORT}:${PSQL_PORT}
  #   environment:
  #     PGPORT: ${PSQL_PORT}
  #     POSTGRES_PORT: ${PSQL_PORT}
  #     PGPASSWORD: ${PSQL_PASS}
  #     POSTGRES_USER: ${PSQL_USER}
  #     POSTGRES_PASSWORD: ${PSQL_PASS}
  #     PGDATABASE: ${PSQL_DBNAME}
  #     POSTGRES_DB: ${PSQL_DBNAME}
  #   volumes:
  #     - ./docker/init/db/realtime.sql:/docker-entrypoint-initdb.d/migrations/99-realtime.sql:Z
  #     # Must be superuser to create event trigger
  #     - ./docker/init/db/webhooks.sql:/docker-entrypoint-initdb.d/init-scripts/98-webhooks.sql:Z
  #     # Must be superuser to alter reserved role
  #     - ./docker/init/db/roles.sql:/docker-entrypoint-initdb.d/init-scripts/99-roles.sql:Z
  #     # PGDATA directory is persisted between restarts
  #     - ./docker/data/db/data:/var/lib/postgresql/data:Z
