version: '3.8'
services:
  server:
    container_name: heiwadai-server
    tty: true
    env_file: ./.env
    build:
      context: .
      dockerfile: ./docker/Dockerfile/server/Dockerfile
    volumes:
      - ./server:/server
    ports:
      - 3000:3000
  pgadmin:
    user: root
    container_name: heiwadai-pgadmin
    image: dpage/pgadmin4:7.3
    environment:
      PGADMIN_DEFAULT_EMAIL: sutefu23@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      TZ: Asia/Tokyo
    volumes:
      - ./docker/data/pgadmin:/var/lib/pgadmin
    ports:
      - 8080:80
    depends_on:
      - db
  db:
    container_name: supabase-db
    image: supabase/postgres:15.1.0.90
    restart: unless-stopped
    ports:
      - ${PSQL_PORT}:${PSQL_PORT}
    environment:
      PGPORT: ${PSQL_PORT}
      POSTGRES_PORT: ${PSQL_PORT}
      PGPASSWORD: ${PSQL_PASS}
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASS}
      PGDATABASE: ${PSQL_DBNAME}
      POSTGRES_DB: ${PSQL_DBNAME}
    volumes:
      - ./docker/init/db/realtime.sql:/docker-entrypoint-initdb.d/migrations/99-realtime.sql:Z
      # Must be superuser to create event trigger
      - ./docker/init/db/webhooks.sql:/docker-entrypoint-initdb.d/init-scripts/98-webhooks.sql:Z
      # Must be superuser to alter reserved role
      - ./docker/init/db/roles.sql:/docker-entrypoint-initdb.d/init-scripts/99-roles.sql:Z
      # PGDATA directory is persisted between restarts
      - ./docker/data/db/data:/var/lib/postgresql/data:Z
  proteus:
    user: root
    container_name: heiwadai-proteus
    image: golang:1.8-jessie
    tty: true
    command: bash
    volumes:
      - ./server:/server