version: '3.8'
services:
  server:
    container_name: heiwadai-server
    tty: true
    env_file: ./.env
    build:
      context: .
      dockerfile: ./docker/Dockerfile/server/Dockerfile
    volumes:
      - ./server:/server
    ports:
      - 3000:3000
  db:
    container_name: heiwadai-db
    image: postgres:15.1-alpine
    volumes:
      - ./docker/data/db:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  pgadmin:
    user: root
    container_name: heiwadai-pgadmin
    image: dpage/pgadmin4:7.3
    environment:
      PGADMIN_DEFAULT_EMAIL: sutefu23@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      TZ: Asia/Tokyo
    volumes:
      - ./docker/data/pgadmin:/var/lib/pgadmin
    ports:
      - 8080:80
    depends_on:
      - db
